repos:
- repo: https://github.com/ambv/black
  rev: 24.3.0
  hooks:
  - id: black
    name: black
    args: [--line-length=110, --skip-string-normalization]
    stages: [pre-commit]
    language_version: python3
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort (python)
- repo: local
  hooks:
    # https://pylint.pycqa.org/en/latest/user_guide/installation/pre-commit-integration.html
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "-j=1",  # Don't run in parallel. Default=0 (aka cpu_core_count)
        ]
    - id: insert-task-number-msg
      name: task number (prepare msg)
      stages: [prepare-commit-msg]
      entry: ./code_checks/checks/task_number_prepare_msg.sh
      language: system
      files: ''
