version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    container_name: web
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    restart: always
    volumes:
      - .:/app
    networks:
      - app_network
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
