# Generated by Django 5.1.2 on 2024-10-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('wallets', '0002_wallet_wallet_label_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet'], name='transaction_wallet_idx'),
        ),
    ]
