# Generated by Django 5.1.2 on 2024-10-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['label'], name='wallet_label_idx'),
        ),
    ]
